# Generated by Django 2.2.12 on 2020-05-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(error_messages={'unique': 'This State already exists'}, max_length=300, unique=True)),
                ('state_image', models.ImageField(upload_to='assets/media/')),
            ],
        ),
        migrations.CreateModel(
            name='StateCrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_image', models.ImageField(upload_to='assets/media/')),
                ('crop_description', models.TextField()),
                ('fertilizers', models.CharField(max_length=600)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='crops.States')),
            ],
        ),
    ]
