# Generated by Django 2.2.12 on 2020-05-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statecrops',
            name='crop_name',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
