# Generated by Django 2.2.12 on 2020-05-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_statecrops_crop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statecrops',
            name='fertilizers',
            field=models.TextField(),
        ),
    ]
