# Generated by Django 2.2.12 on 2020-05-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovtDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(max_length=800)),
            ],
        ),
    ]
