# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-13 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import razorpay_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('basket_id', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('currency_type', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(max_length=50)),
                ('razorpay_id', models.CharField(blank=True, db_index=True, max_length=22, null=True)),
                ('error_code', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.CharField(blank=True, max_length=256, null=True)),
                ('transaction_id', models.CharField(db_index=True, default=razorpay_api.models.generate_id, max_length=64)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-transaction_date',),
            },
        ),
    ]
